home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.coming_soon, name='coming_soon'),
    path('<str:invalid_url>/', views.handle_404, name='handle_404'),
]

k1comingsoon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/models.py
from django.db import models

class Subscriber(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

home/forms.py
from django import forms

class SubscribeForm(forms.Form):
    email = forms.EmailField(label='Email')

home/views.py
from django.shortcuts import render
from .forms import SubscribeForm
from .models import Subscriber

def coming_soon(request):
    form = SubscribeForm()
    if request.method == 'POST':
        form = SubscribeForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            subscriber = Subscriber.objects.create(email=email)
            subscriber.save()
            return render(request, 'home/thank_you.html')
    return render(request, 'home/index.html', {'form': form})

def handle_404(request, invalid_url):
    return render(request, '404/404.html')

home/templates/home/index.html
{% load static %}
{% load widget_tweaks %}
<!doctype html>
<html lang=en>
<head>
    <meta charset=UTF-8 />
    <meta name=description content="Free coming soon template">
    <meta name=author content="Pawel Zuchowski">
    <meta name=viewport content="width=device-width,initial-scale=1" />
    <meta http-equiv=X-UA-Compatible content="ie=edge" />
    <link rel=stylesheet href=https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css
        integrity=sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO crossorigin=anonymous>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel=stylesheet>
    <link href="https://fonts.googleapis.com/css2?family=Muli:wght@300;700&display=swap" rel=stylesheet>
    <link rel=stylesheet href="https://fonts.googleapis.com/css?family=Roboto&display=swap">
    <script src=https://kit.fontawesome.com/3c09bcb51a.js></script>
    <title>به زودی</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="loading-screen">
        <div class="loading-icon">
            <img src="{% static 'images/k1s_logo.png' %}" alt="Your Logo" class="logo">
        </div>
    </div>
    <div class=container>
        <div class=row>
            <div class="left-wrap col-12 col-md-5">
                <div class=left>
                    <p><span class=days></span><span class=small> days</span></p>
                    <p><span class=hours></span><span class=small> hours</span></p>
                    <p>&nbsp;&nbsp;<span class=minutes></span><span class=small> minutes</span></p>
                    <p>&nbsp;&nbsp;<span class=seconds></span><span class=small> seconds</span></p>
                </div>
            </div>
            <div class="col-12 col-md-7 right">
                <div class=mainInfo>
                    <div class="logo-container">
                        <img src="{% static 'images/k1s_logo.png' %}" alt="Your Logo" class="logo">
                    </div>
                    <h1>. . . منتظرمان باشید</h1>
                    <p class="slogan">
                        در حال طراحی جامع ترین سایت ایمنی، بهداشت و محیط زیست هستیم <br>
                        شگفت زده خواهید شد<br>
                        برای استعلام و ثبت سفارش با شماره <a class="phone-number" href="tel:09309694154">۰۹۳۰۹۶۹۴۱۵۴</a> تماس حاصل نمایید<br>
                        برای به روز ماندن در خبرنامه ما عضو شوید
                    </p>
                    <form class="form-subscribe" method="post" action="{% url 'home:coming_soon' %}">
                        {% csrf_token %}
                        {{ form.email|attr:"placeholder:ایمیل را وارد کنید"|add_class:"form" }}
                        <button type="submit">عضویت</button>
                    </form>
                </div>
                <ul class=icon-list>
                    <li class=icon><a class=linkedin href="https://www.linkedin.com/in/keyvan-environmental-solutions-988a52260/"></a></li>
                    <li class=icon><a class=telegram href="https://t.me/keyvansafe"></a></li>
                    <li class=icon><a class=instagram href="https://www.instagram.com/keyvansafe"></a></li>    
                </ul>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
 
</body>

</html>

home/templates/home/thank_you.html
{% load static %}
<!doctype html>
<html lang=en>
<head>
    <meta charset=UTF-8 />
    <meta name=description content="Free coming soon template">
    <meta name=author content="Pawel Zuchowski">
    <meta name=viewport content="width=device-width,initial-scale=1" />
    <meta http-equiv=X-UA-Compatible content="ie=edge" />
    <link rel=stylesheet href=https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css
        integrity=sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO crossorigin=anonymous>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel=stylesheet>
    <link href="https://fonts.googleapis.com/css2?family=Muli:wght@300;700&display=swap" rel=stylesheet>
    <link rel=stylesheet href="https://fonts.googleapis.com/css?family=Roboto&display=swap">
    <script src=https://kit.fontawesome.com/3c09bcb51a.js></script>
    <title>به زودی</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="loading-screen">
        <div class="loading-icon">
            <img src="{% static 'images/k1s_logo.png' %}" alt="Your Logo" class="logo">
        </div>
    </div>
    <div class=container>
        <div class=row>
            <div class="left-wrap col-12 col-md-5">
                <div class=left>
                    <p><span class=days></span><span class=small> days</span></p>
                    <p><span class=hours></span><span class=small> hours</span></p>
                    <p>&nbsp;&nbsp;<span class=minutes></span><span class=small> minutes</span></p>
                    <p>&nbsp;&nbsp;<span class=seconds></span><span class=small> seconds</span></p>
                </div>
            </div>
            <div class="col-12 col-md-7 right">
                <div class=mainInfo>
                    <div class="logo-container">
                        <img src="{% static 'images/k1s_logo.png' %}" alt="Your Logo" class="logo">
                    </div>
                    <h1>متشکریم</h1>
                    <p class="slogan">از اینکه در خبرنامه ما عضو شدید سپاسگزاریم<br>
                    برای استعلام و ثبت سفارش با شماره <a class="phone-number" href="tel:09309694154">۰۹۳۰۹۶۹۴۱۵۴</a> تماس حاصل نمایید
                    </p>
                </div>
                <ul class=icon-list>
                    <li class=icon><a class=linkedin href="https://www.linkedin.com/in/keyvan-environmental-solutions-988a52260/"></a></li>
                    <li class=icon><a class=telegram href="https://t.me/keyvansafe"></a></li>
                    <li class=icon><a class=instagram href="https://www.instagram.com/keyvansafe"></a></li>                    
                </ul>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
 
</body>

</html>